### ISSUE TITLE
Can not downgrade from 4/5 to 3 on 10.9.11 FreeBSD

### ISSUE THREAD

**Issue by make-nz** [jellyfin/jellyfin-plugin-dlna#100]
I can not downgrade from v4/5 to 3 on 10.9.11 FreeBSD

![Image](https://github.com/user-attachments/assets/950743a6-5260-441f-ad89-cd8563c8e74d)

![Image](https://github.com/user-attachments/assets/43bc352a-6422-4747-9d6b-391e7f15d689)

**Comment by thornbill** [comment]
As noted [here](https://github.com/jellyfin/jellyfin-plugin-dlna/issues/99#issuecomment-2465275199) these versions are not supported by that server version.
