### ISSUE TITLE
Additional logging for DLNA device info before matching with a profile

### ISSUE THREAD

**Issue by aoberoi** [jellyfin/jellyfin-plugin-dlna#31]
First, I am willing to contribute and help land this change. It will likely be a tiny one-liner. If I see some general agreement, esp from the core team, then I'll dive into the code and work on a PR.

Currently, DLNA profile matching is sort of a guess-and-check process, and encourages folks to be somewhat loose/sloppy with defining a custom profile to match their specific devices. Right now, I have no idea what fields in the UI such as Manufacturer, Model Name, Model Number, etc. are even matched against. The only fields that seem to be approachable are the headers, because headers are output in some existing logs today.

In my opinion, logging out exhaustive info about a connected device, even if its going to match to a generic default profile, would help folks craft more useful profiles. These would be specific enough to address a whole family of devices with the same capabilities (which will continue to evolve as new hardware comes out and new software for existing hardware also comes out). With better quality custom profiles, people might actually be able to share them with each other or back to the server project. I could see potential for a better UI being developed around this, but I think the first step is just a simple log line with as much detail as possible about DLNA devices.

It seems like the DLNA code might be moving out of this repo (see: jellyfin/jellyfin#10558). Let me know if I need to target a different branch or repo to help align with that work. Thanks!

**Comment by spali** [comment]
I appreciate the logging of the profile.
Maybe in a second step, why not let us show the profile details in the current device list and let us create a prefilled profile from there.

**Comment by ghdoca** [comment]
Any feedback on this one?
I can't get the custom profiles to work and no usable debug output.
Always getting: Jellyfin.Plugin.Dlna.DlnaManager: No matching device profile found. The default will need to be used.

**Comment by disgustipated** [comment]
@ghdoca after you see that line there should be some output that indicates the friendlyname of the device that did not match a profile. you can use that to create a profile with a matching friendlyname value in the xml. Example the below matches to a device that starts with LG in the friendly name
```
  <Identification>
    <FriendlyName>LG*</FriendlyName>
    <Headers>
      <HttpHeaderInfo name="User-Agent" value="LG" match="Substring" />
    </Headers>
  </Identification>
```

**Comment by ghdoca** [comment]
I got it working when putting the xml files in jellyfin/plugins/DLNA_3.0.0.0/profiles/

**Comment by disgustipated** [comment]
It seems the profiles were moved to the plugin folder, i cant yet find where user profiles are used for this, with each update to the plugin the profiles remain in the old plugin folder. i'll have to poke around to see how the user profile is now mapped as it doesnt seem to be picking up in a spot that can be used outside of the plugin directory. previously there were two folders, system and user profiles.

**Comment by disgustipated** [comment]
This is the location of where the plugin uses for user profiles by default: 
/config/plugins/configurations/dlna/user/

Its set by this config value in server but I cant seem to find a ui element to set this, perhaps its still usable through env vars
PluginConfigurationsPath

**Comment by ghdoca** [comment]
Putting the xml in jellyfin/config/plugins/configurations/dlna/user does not work for me (Debian 12, latest Docker image)
For it to work I have to put the xml in jellyfin/plugins/DLNA_4.0.0.0/profiles/

**Comment by disgustipated** [comment]
Interesting, I just used it this morning and it picked up my profiles. I'll add some debug logging so that someone can see what paths are being used.
