### ISSUE TITLE
Request: installed plugin shows current version, and hides or replaces the devices->DLNA menu entry

### ISSUE THREAD

**Issue by systemcrash** [jellyfin/jellyfin-plugin-dlna#45]
I think in general that plugin info should appear [here](https://github.com/jellyfin/jellyfin-web/issues/5436)

**Comment by systemcrash** [comment]
Also, this is really confusing for users (jellyfin problem, not specific to this plugin):

![Screenshot 2024-05-12 at 20 32 05](https://github.com/jellyfin/jellyfin-plugin-dlna/assets/647633/bc3c4f21-933b-4bbe-bbd4-24bad16fc267)

**Comment by crobibero** [comment]
You were expected to remove the unstable plugin repo when upgrading to 10.9.

What you are asking for is not possible with how Jellyfin works.

**Comment by systemcrash** [comment]
How about having a chdckbox en/disable. It's not like anyone was telling me
to do that.
