### ISSUE TITLE
dlna menu is empty despite dlna plugin is installed and active

### ISSUE THREAD

**Issue by gazsoimi** [jellyfin/jellyfin-plugin-dlna#57]
Jellífin linuxserver docker 10.9.4 but the same problem with original jellyfin repo
fresh install

---
version: "2.1"
services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    group_add:
     - "104"
     - "44"
     
    environment:    
      - TZ:Europe/Budapest
      - JELLYFIN_PublishedServerUrl=10.90.94.9 
      - ROC_ENABLE_PRE_VEGA=1
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    network_mode: host

    volumes:
      - /mnt/docker/jellyfin:/config
      - /mnt/mozi:/data
     
    
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

    restart: always

[_jellyfin_logs(3).txt](https://github.com/user-attachments/files/15526920/_jellyfin_logs.3.txt)

dlna plugin installed, server rebooted many times. dlna menu has no submenu and offers me to download the plugin, which is already installed.

![kép](https://github.com/jellyfin/jellyfin-plugin-dlna/assets/12159424/caafdacd-481c-4a63-93ef-6a9f76fdc147)

**Comment by gazsoimi** [comment]
![kép](https://github.com/jellyfin/jellyfin-plugin-dlna/assets/12159424/37b8aeca-c12d-4929-ac84-cf22726d3b04)

**Comment by thornbill** [comment]
This page is just a placeholder to direct people used to configuring DLNA in this way in previous releases. Once you install the plugin, you configure it in the same way as every other plugin. The page will be removed entirely in the 10.10 release.

**Comment by gazsoimi** [comment]
ok, from youtube videos i was under the assumption, that after installing the plugin, there will be submenus there, with profile configs.

**Comment by thornbill** [comment]
This page was removed in 10.10 as planned.
