### ISSUE TITLE
No more DLNA profiles?

### ISSUE THREAD

**Issue by seemebreakthis** [jellyfin/jellyfin-plugin-dlna#58]
I just realized DLNA is now a plugin.

With the old DLNA feature, you were able to define custom profiles.  And I used to have a profile with my TV to force it to transcode (to be able to play some audio / video formats) and have subtitles burnt into the video.

But now it seems the entire profile tab is gone?  And sure enough I tested some videos and they no longer play properly on my (old) Sony Bravia TV.

Hmm... I guess there is no way around this, but just thought I raise an issue here for that 0.00001% chance there is some workaround?

**Comment by thornbill** [comment]
Duplicate of https://github.com/jellyfin/jellyfin-plugin-dlna/issues/49
