### ISSUE TITLE
DLNA ins't discovered properly by clients and control points

### ISSUE THREAD

**Issue by ypopovych** [jellyfin/jellyfin-plugin-dlna#64]
In my setup Jellyfin works as Podman container with host network.

Network supports both, IPv6 and IPv4. I added local IP subnets for IPv4 and IPv6 in the Jellyfin settings.

DLNA renderers properly discovered by Jellyfin and I can play to them, but Jellyfin isn't properly discovered by control points or clients.

It can be discovered only with `Blast Alive Messages` enabled. Seems as it doesn't respond to "ssdp:discover" message (or message is dropped somewhere).

I tested it with BubbleUPnP and it needs blast alive message to be sent to appear in the list, but all other DLNA devices appear instantly.

Main problem that I have software that ignores "alive" messages and relies only on "discover", and it can't discover media server at all.

Could it be that I missing something in the settings?

**Comment by ypopovych** [comment]
I tested it with "UPnP Analyzer" app from the Apple App Store. Jellyfin doesn't respond to "ssdp:discover".

I got response from the all of my DLNA devices (even router sent info about Layer3Forwarding) but no response from the Jellyfin

**Comment by SpiReCZ** [comment]
Jellyfin 10.9.9, DLNA plugin 2.0.0.0, docker network mode `host` and no device can see DLNA server on the network. In 10.8 without issues, even tried binding network ips directly as someone suggested elsewhere https://github.com/jellyfin/jellyfin/issues/11791 https://github.com/jellyfin/jellyfin-plugin-dlna/issues/48

**Comment by Nullcaller** [comment]
I was trying to test whether they fixed Jellyfin's DLNA server implementation not working with Bigscreen (still doesn't work, btw, errors out with the message "path couldn't be accessed" or something along those lines), and for some reason Bigscreen just didn't see the DLNA server at all until I changed the IP bindings field from empty to "<LAN IP (10.x.x.x)>, 127.0.0.1", as suggested in #48. I didn't test it that rigorously, though, so I might be wrong.

**Comment by disgustipated** [comment]
Is this still a problem with v3?

**Comment by opapanik** [comment]
Hi yes it seems there is a problem on some devices. My bubbleupnp detects it, but not my TV or.. Windows 10 (yeah I know, but its a clue right? :)

MiniDLNA on the other hand (which I have to use because jellyfin DLNA does not support search) is correctly and promptly identified by all my devices. So there's something going on.

I do not use a baseurl (used to but stopped becasuse of the problems).

**Comment by SpiReCZ** [comment]
> Is this still a problem with v3? I just used bubbleupnp and jellyfin showed up. There were some changes with the publishing url. If v3 does not work are you using a baseurl? if so try the patch here #74

I only made DLNA working with v3 while settings: Blast Alive Messages 30 sec, Client Discovery Interval: 20 sec
And sometimes it takes or minute or two to be shown in the LG TV..
Other than that DLNA server would not ever show.

**Comment by disgustipated** [comment]
> I only made DLNA working with v3 while settings: Blast Alive Messages 30 sec, Client Discovery Interval: 20 sec And sometimes it takes or minute or two to be shown in the LG TV.. Other than that DLNA server would not ever show.

ok, did you try the zip i attached?

**Comment by ypopovych** [comment]
@disgustipated I checked with attached zip - it works now. Server properly answered on the `ssdp:discover` message

**Comment by disgustipated** [comment]
Awesome, I think this will fix a few other issues some are experiencing too. I'll make a PR but it might be nice for others to test as it seems some have some unique network setups.

**Comment by Elyviere** [comment]
I gave it a try from the Bigscreen Beyond VR app in a Valve Index. It took a few refreshes after adding the files in your .zip, but it did show up in the end. 

However, I was still unable to connect to the DLNA server, getting an error message on attempting to do so. This might just be an issue on Bigscreen's end though, as I found this thread with someone having a similar error: https://forum.jellyfin.org/t-jellyfin-on-bigscreen-vr

**Comment by disgustipated** [comment]
@Elyviere So previously it would not show up in the index app? I have an index so ill see if i can find some time to try that app, but yeah the rest of that might be a different issue.

**Comment by Elyviere** [comment]
Exactly, without your zip files I was unable to find the jellyfin server at all.

After some googling I found the developer of Beyond saying that Jellyfin's implementation of DLNA is non-standard and that they therefore don't support connecting to it.

**Comment by Nullcaller** [comment]
> Exactly, without your zip files I was unable to find the jellyfin server at all.

When I wrote that Bigscreen couldn't find Jellyfin without me explicitly setting the IP address, I tested it with v3 of the DLNA plugin and with the "Bigscreen Beta" app on Quest 2.

As previously stated, it eventually showed up when I set the IP. So that's weird. Or maybe I don't understand something...

The server I was running this on also hosts a Plex instance. I believe I shut it off during testing, but I can't say I remember that part very well by now.

I'll try the zip file today and report on my findings.

**Comment by Nullcaller** [comment]
Also, @disgustipated if you could point me in the general direction of where it is in the source code that the directory structure is set for the DLNA server, I'd appreciate it greatly. I tried just jumping into the code before, but got nowhere, unfortunately.

When I first installed Jellyfin (it was before DLNA was sectioned off into a plugin) I was desperate to get it working with Bigscreen, so I took a few packet captures (DLNA is just unencrypted HTTP, luckily) and it seemed to me at the time like the captures of Plex DLNA (which worked) and of Jellyfin DLNA (which didn't) were pretty much identical, except for directory structure. I then wanted to play around with the code, but life got in the way.

The suspicion that it's the directory structure is also indirectly confirmed by the fact that the actual error message displayed by Bigscreen is something along the lines of "Error - path couldn't be accessed".

So if I could play around with the respective code while having the actual erroring device in hand, maybe I would be able to put together a PR or at least a fork that works with Bigscreen.

**Comment by disgustipated** [comment]
I'd suggest logging a separate issue as this one is about the ssdp discovery which is a separate part of the code from listing the directory. i believe that message is from bigscreen though so maybe their app has some debugging that can give you more detail. Just going off memory i think what youre asking is around the didl section in the jf dlna plugin.

**Comment by Nullcaller** [comment]
> i believe that message is from bigscreen though so maybe their app has some debugging that can give you more detail. Just going off memory i think what youre asking is around the didl section in the jf dlna plugin.

Thank you!

> I'd suggest logging a separate issue as this one is about the ssdp discovery which is a separate part of the code from listing the directory.

Yup, will do. I just wanted to gather some data and make an attempt (however little) to fix and/or analyze it first, so that the issue I open isn't just an elaborate "pls fix".

**Comment by Nullcaller** [comment]
Can confirm. With respective files in the plugin folder replaced with the ones from the zip above, discovery works properly in Bigscreen on Quest 2, without needing to enter anything into the "Bind to local network addresses" field. It feels like it works faster, too.

**Comment by philS1** [comment]
On Commedia (Quest 3) I can see the jellyfin dlna connection and browse folders but in each folder the Commedia clains there is no media.

On Bigscreen I can't find the dlna server at alll although I replaced the dll files with those from the zip archive and restarted Jellyfin. How can I add the server to Bigscreen manually?

**Comment by ionutvilie** [comment]
Hi @disgustipated I tested the artifact from the latest [pr-82 build](https://github.com/jellyfin/jellyfin-plugin-dlna/actions/runs/11473845690?pr=82)  and it seems to only bind/register on the loopback interface. 

I think I wrote on another issue a while back. Since then I started to use the Android app but I have a secondary TV that only works with DLNA. I'm running Jellyfin in a microk8s set-up  with multus to register an interface on the local-network for SSDP broadcast.  

```bash
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Playback, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_3.0.0.0/Jellyfin.Plugin.Dlna.Playback.dll
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_3.0.0.0/Jellyfin.Plugin.Dlna.dll
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Rssdp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_3.0.0.0/Rssdp.dll
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly Jellyfin.Plugin.Dlna.Model, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null from /config/plugins/DLNA_3.0.0.0/Jellyfin.Plugin.Dlna.Model.dll
[18:33:43] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[18:33:43] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[18:33:43] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[18:33:43] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: []
[18:33:43] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]
[18:33:43] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is Allowlist
[18:33:43] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Filtered subnets: []
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: DLNA 3.0.0.0
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.9.11.0
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.9.11.0
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.9.11.0
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.9.11.0
[18:33:43] [INF] [10] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.9.11.0
[18:33:43] [INF] [10] Main: Kestrel is listening on 0.0.0.0
[18:33:43] [INF] [10] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 127.0.0.1 with uri http://127.0.0.1:8096/dlna/81546802-17fe-4759-b571-28ee5b9a862d/description.xml
[....]
[18:33:44] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[18:33:44] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
[18:33:44] [INF] [10] Emby.Server.Implementations.ApplicationHost: ServerId: 8154680217fe4759b57128ee5b9a862d
[18:33:44] [INF] [10] Emby.Server.Implementations.ApplicationHost: Core startup complete
[18:33:44] [INF] [10] Main: Startup complete 0:00:01.5165338
[18:33:47] [INF] [25] Emby.Server.Implementations.ScheduledTasks.TaskManager: Clean up collections and playlists Completed after 0 minute(s) and 0 seconds
[18:33:47] [INF] [10] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 0 seconds
[18:34:36] [INF] [10] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.100.32 request
[18:34:36] [WRN] [25] Jellyfin.Networking.Manager.NetworkManager: 192.168.100.32: Only loopback 127.0.0.1 returned, using that as bind address.
[18:36:22] [WRN] [25] Jellyfin.Networking.Manager.NetworkManager: 192.168.100.32: Only loopback 127.0.0.1 returned, using that as bind address.
[18:36:26] [INF] [122] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.100.32 closed
```
Below is the container network set-up. 
I have tested the same cluster with [gerbera](https://docs.gerbera.io/en/stable/config-server.html#interface) that can only brodcast on one interface and it does on net1 with success. 
As a workaround I use [rclone](https://rclone.org/commands/rclone_serve_dlna/) to serve the content over DLNA. 
Previous to jellyfin 1.9 it used to work just fine so it doesn't seem to be my set-up. 

```bash
root@jellyfin-0:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3: eth0@if26: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 5a:5e:d5:2c:40:cf brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.1.191.193/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::585e:d5ff:fe2c:40cf/64 scope link
       valid_lft forever preferred_lft forever
4: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 62:27:07:12:34:e2 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.100.220/24 brd 192.168.100.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fd14:b9ed:2835:623f:6027:7ff:fe12:34e2/64 scope global dynamic mngtmpaddr
       valid_lft 1760sec preferred_lft 1760sec
    inet6 fe80::6027:7ff:fe12:34e2/64 scope link
       valid_lft forever preferred_lft forever
```

I have 0 knowledge when it comes to C# so I can't be of much help but I can test other builds, feel free to tag me if needed.

**Comment by disgustipated** [comment]
Thats curious as there is a line that specifically excludes loopback 
 .Where(x => !x.Address.Equals(IPAddress.Loopback))

I'll add some logging around the validinterfaces to get a better idea on what yours is doing. looks like you have 0.0.0.0 specified for the bind address and i suspect that might be doing something to how the valid ip is selected when it calls _networkManager.GetInternalBindAddresses() from JF server, which the lines in your log from Jellyfin.Networking.Manager.NetworkManager seem to indicate the same. if youre able to test, can you try removing 0.0.0.0 from the bind ip?

**Comment by Nullcaller** [comment]
It appears to fall back to loopback interface [here](https://github.com/jellyfin/jellyfin-plugin-dlna/pull/82/files#diff-a5763f20531db618e1015248df46c6c4d64fc2c66c05eb3d9d3b933ef77e29bdR257-R261)

**Comment by disgustipated** [comment]
Yep, which means for some reason it didn't pick up any valid ones in the criteria above it

**Comment by Nullcaller** [comment]
I know the reason.

> ```shell
> [18:33:43] [INF] [10] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: []
> ```

It's because for some other reason, Jellyfin didn't pick up any interfaces. This log line is printed [here](https://github.com/jellyfin/jellyfin/blob/abd6649e5d55ea0a582f4c3042466b352d5998d0/src/Jellyfin.Networking/Manager/NetworkManager.cs#L1147), and it uses the same variable as NetworkManager does [here](https://github.com/jellyfin/jellyfin/blob/abd6649e5d55ea0a582f4c3042466b352d5998d0/src/Jellyfin.Networking/Manager/NetworkManager.cs#L884) when returning addresses to the plugin in `GetInternalBindAddresses`.

**Comment by Nullcaller** [comment]
@ionutvilie Try enabling [debug logging](https://jellyfin.org/docs/general/administration/troubleshooting/#debug-logging). Upon restart, it should poop out a lot more information about interfaces. Upload the log to pastebin, post the link here and I'll give it a look, just to make sure, and maybe find out why it's not detecting interfaces. Don't forget to disable debug logging unless you want five petabytes of logs to be generated by the end of the year.

**Comment by ionutvilie** [comment]
The issue with not binding Jellyfin on `0.0.0.0` (all interfaces) is that the k8s routing ingress will not work. the request will be sent on the k8s managed network interface (`10.x.x.x`) and, no process is listening on that interface. 

A small test and binding on `192.168.100.220` seems to work fine (play test of about 1 to 2m).
- Sony with Android - works 
- Samsung - works
- VLC on my mobile phone is not able to discover it while rclone is there.

With the above test, I have found the issue, in "Bind to local network address" I had configured 0.0.0.0 (probably work habit), if I leave the field blank as stated in the description, DLNA plugin binds to all interfaces. :| 

```bash
--> this changed: [09:23:14] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "10.1.191.193", "192.168.100.220"]
[09:23:14] [INF] [29] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]

[09:23:35] [INF] [22] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 127.0.0.1 with uri http://127.0.0.1:8096/dlna/81546802-17fe-4759-b571-28ee5b9a862d/description.xml
[09:23:35] [INF] [22] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 10.1.191.193 with uri http://10.1.191.193:8096/dlna/81546802-17fe-4759-b571-28ee5b9a862d/description.xml
[09:23:35] [INF] [22] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.100.220 with uri http://192.168.100.220:8096/dlna/81546802-17fe-4759-b571-28ee5b9a862d/description.xml
```

I can run the debug at this point, but this seems just an issue on my side both `:8096` and `0.0.0.0:8096` use cases are accepted to bind on all interfaces AFIK.

**Comment by SpiReCZ** [comment]
> The issue with not binding Jellyfin on `0.0.0.0` (all interfaces) is that the k8s routing ingress will not work. the request will be sent on the k8s managed network interface (`10.x.x.x`) and, no process is listening on that interface.
> 
> With the above test, I have found the issue, in "Bind to local network address" I had configured 0.0.0.0 (probably work habit), if I leave the field blank as stated in the description, DLNA plugin binds to all interfaces. :|
> 
> I can run the debug at this point, but this seems just an issue on my side both `:8096` and `0.0.0.0:8096` use cases are accepted to bind on all interfaces AFIK.

**The issue for me and many others is not with binding to 0.0.0.0. As that sometimes works and sometimes don't with the same interfaces. These hacks to bind interface forcefully are not a solution and don't work reliably or at all.** 

I'm using plain Docker with `network_mode: "host"`, same as many others. And the issue seems to be related to number of available interfaces and timing of the SSDP:NOTIFY multicast packets (network_count * interval would be to obvious?).

I had to set very low intervals `Client Discovery Interval: 20`, `Blast Alive Messages: true`, `Alive Message Interval: 30` for SSDP to work at all.

```txt
[10:13:09] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

[10:13:09] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []

[10:13:09] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Used LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]

[10:13:09] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filtered interface addresses: ["127.0.0.1", "192.168.2.222", "172.25.0.1", "172.21.0.1", "172.19.0.1", "172.17.0.1"]

[10:13:09] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Bind Addresses ["0.0.0.0"]

[10:13:47] [INF] [1] Main: Kestrel is listening on 0.0.0.0

[10:13:47] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 127.0.0.1 with uri http://127.0.0.1:8096/dlna/123-45-abc/description.xml

[10:13:47] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 192.168.2.222 with uri http://192.168.2.222:8096/dlna/123-45-abc/description.xml

[10:13:47] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.25.0.1 with uri http://172.25.0.1:8096/dlna/123-45-abc/description.xml

[10:13:47] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.21.0.1 with uri http://172.21.0.1:8096/dlna/123-45-abc/description.xml

[10:13:47] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.19.0.1 with uri http://172.19.0.1:8096/dlna/123-45-abc/description.xml

[10:13:47] [INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for urn:schemas-upnp-org:device:MediaServer:1 on 172.17.0.1 with uri http://172.17.0.1:8096/dlna/123-45-abc/description.xml
```

**Comment by disgustipated** [comment]
@SpiReCZ can you confirm youre using either the zip i previously attached zip or this build artifact? https://github.com/jellyfin/jellyfin-plugin-dlna/actions/runs/11473845690?pr=82

my setup is using docker with network mode host, clent discovery 150, blast alive is off. my only value set in JF server is the lan network because im using a non standard local ip. my server shows up instantly in bubbleupnp, vlc, and lgtv dlna browser. are you saying youre still not getting ssdp:discovery response with the listed build item?

**Comment by ionutvilie** [comment]
@SpiReCZ 

> And the issue seems to be related to number of available interfaces and timing of the SSDP:NOTIFY multicast packets (network_count * interval would be to obvious?).

you could also try using macvlan, I overengineered my current set-up but this is what I used before (I don't remember how many nic's the container used to have):  https://github.com/ionutvilie/awesome-home-server/blob/master/ak1pro/docker-compose.yml#L142

**Comment by SpiReCZ** [comment]
> @SpiReCZ can you confirm youre using either the zip i previously attached zip or this build artifact? https://github.com/jellyfin/jellyfin-plugin-dlna/actions/runs/11473845690?pr=82
> 
> my setup is using docker with network mode host, clent discovery 150, blast alive is off. my only value set in JF server is the lan network because im using a non standard local ip. my server shows up instantly in bubbleupnp, vlc, and lgtv dlna browser. are you saying youre still not getting ssdp:discovery response with the listed build item?
> 
> i also just forced all ips with the below as lan networks in jf server to make my setup bind to everything with this and it still showed up instantly, however this is only to mimic your theory of timing as the ip my network works on is the 6.13 network 127.0.0.1/24, 6.13.0.0/24, 10.16.0.0/24, 10.26.0.0/24, 172.18.0.0/24

I was using regular 3.0.0.0 official build, as downloading some ZIP might not be the beast idea. I installed the build artifact and for now it appears to be working with similar plugin settings you mentioned. Will have to test it for a few days.

**Comment by Nullcaller** [comment]
> downloading some ZIP might not be the best idea

I mean, yeah... But also, no... We already know official v3 as it stands is borked when it comes to SSDP discovery. The zip, on the other hand, contains fixes made by disgustipated that make the SSDP discovery work again. If you don't trust the zip file, you may review the code in pull request #82 yourself, then download an artifact for that build from GitHub action. It is essentially built by the maintainers of this repository, and is sort of officially nothing more and nothing less than the code in PR #82, compiled and packaged.

**Comment by SpiReCZ** [comment]
> > downloading some ZIP might not be the best idea
> 
> I mean, yeah... But also, no... We already know official v3 as it stands is borked when it comes to SSDP discovery. The zip, on the other hand, contains fixes made by disgustipated that make the SSDP discovery work again. If you don't trust the zip file, you may review the code in pull request #82 yourself, then download an artifact for that build from GitHub Actions. It is essentially built by the maintainers of this repository, and is sort of officially nothing more and nothing less than the code in PR #82, compiled and packaged.

I downloaded the CI built one.

**Comment by philS1** [comment]
I'm using the zip file and without enabling the blast setting I can't see the dlna server at in vlc. Why?
I tried both cases, entering the ip in network settings or leaving the field blank.

**Comment by disgustipated** [comment]
@philS1 plz attach your log which should include the startup messages that show how the publisher is being registered, that would be most helpful to find if your issue is something else or if youre having troubles with ssdp:discovery messages which is the scope of this issue.

**Comment by philS1** [comment]
[jellyfin.log](https://github.com/user-attachments/files/17522415/jellyfin.log)

**Comment by disgustipated** [comment]
@philS1 this is the line that shows what is being used for publishing the service
```
[2024-10-25 14:54:51.883 +02:00] [INF] [95] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "192.168.178.79" with uri "http://192.168.178.79:8096/dlna/b149d7df-790f-4c4a-a189-2eeba8c11034/description.xml"
```
Is the device youre using to try and browse dlna on the 192.168.178.0 network? can you load the url listed in a browser and see xml? your log does seem to show plenty of upnp traffic so im not sure your issue is with the discovery

**Comment by Nullcaller** [comment]
It's a weird kind of traffic...

Most of it seems to be coming from something called "fritz!box", which seems to be an ISP-provided router of some sorts, and all of it appears to be responses to `ssdp:discover`. Does the DLNA plugin send out discover messages?

And then there's another weird thing right at the start of the log, where the server is receiving things from 192.168.178.79, which is itself. @philS1, you sure you don't have a loop in your network?

**Comment by philS1** [comment]
@disgustipated 
The description.xml URL i can open fine.

the lan devices are directly in the 192.168.178.0/24 network. My router "fritz!box" also supports upnp. You can put data on an usb stick and connect it to the router. It's not isp provided and can be fully administrated by me.

@Nullcaller 
I made a wireshark dump on the client side and I see ssdp M-Search messages from the server running jellyfin  dlna plugin will send ssdp discover message to the 239.255.255.250 upnp address.

There is no hw loop on the network switches, however maybe docker can produce such a loop maybe?

**Comment by ypopovych** [comment]
Jellyfin sends `ssdp:discover` messages too, not only responds to them. They are needed for "Play to" functionality, so you can send video to the TV or another type of DLNA player

**Comment by Nullcaller** [comment]
I don't think fritzbox sending responses to discovery requests can mess anything up, no... I just wondered why they were there. @philS1, can you make a wireshark packet capture on the host on the server side? Just to confirm that the `ssdp:discover` requests are reaching the server, and to see whether or not the server is sending out anything.

**Comment by Nullcaller** [comment]
Also just to confirm, you are using host mode in docker, right?

**Comment by Nullcaller** [comment]
Also just to confirm, you are using host mode in docker, right?

**Comment by philS1** [comment]
yes, docker network mode.
I can make a wireshark capture on server side but which filter should I use. Only check udp port 1900? Elsewise there's too much data.

**Comment by Nullcaller** [comment]
Something along the lines of

```
udp.port == 1900 || ((ip.addr == <server> && (ip.addr == <client> || ip.addr == <gateway>)) && (((udp.srcport >= 30000) && (udp.dstport >= 30000)) || ((tcp.srcport >= 30000) && (tcp.dstport >= 30000))))
```

should account for everything DLNA-related. So use 

```
udp.port == 1900 || ((ip.addr == 192.168.178.79 && (ip.addr == <client> || ip.addr == 192.168.178.1)) && (((udp.srcport >= 30000) && (udp.dstport >= 30000)) || ((tcp.srcport >= 30000) && (tcp.dstport >= 30000))))
```

but replace `<client>` with the IP of the client you're trying to access the server from.

**Comment by Nullcaller** [comment]
Something along the lines of

```
udp.port == 1900 || ssdp || (((ip.addr == <server> && (ip.addr == <client> || ip.addr == <gateway>)) || (ip.src == <server> && ip.dst == <server>)) && (((udp.srcport >= 30000) && (udp.dstport >= 30000)) || ((tcp.srcport >= 30000) && (tcp.dstport >= 30000))))
```

should account for everything DLNA-related. So use 

```
udp.port == 1900 || ssdp || (((ip.addr == 192.168.178.79 && (ip.addr == <client> || ip.addr == 192.168.178.1)) || (ip.src == 192.168.178.79 && ip.dst == 192.168.178.79)) && (((udp.srcport >= 30000) && (udp.dstport >= 30000)) || ((tcp.srcport >= 30000) && (tcp.dstport >= 30000))))
```

but replace `<client>` with the IP of the client you're trying to access the server from.

**Comment by philS1** [comment]
Here you can also see ssdp packets from my client 192.168.178.117

**Comment by disgustipated** [comment]
I think your filter might be a little too specific. try using only
```
udp contains "HTTP/1.1"
```
This shows both the discover and the responses in a trace on my network and using vlc player
Also @philS1, what are you using to try to find the server? Have you tried other applications like vlc or bubbleupnp?

**Comment by Nullcaller** [comment]
> I think your filter might be a little too specific. try using only
> 
> ```
> udp contains "HTTP/1.1"
> ```

Yeah, I thought DLNA servers/clients only used ports above 30000, and that seems to generally be the case (Bigscreen, VLC, BubbleUPnP, Plex, Jellyfin all seem to be preferring higher ports). But I have very recently discovered, that no, in fact, it can be any port. So thanks for the correct filter.

My two cents in, though: based on the packet capture we have, it does appear that `ssdp:discover` requests from the client are reaching the host; based on the jellyfin log we have, it does not appear that they reach jellyfin (unless somehow something changed between now and then, or the log file is somehow a wrong one). I'd tentatively suspect docker or firewall(s), but I wouldn't truly be sure without a proper packet cpature, with the filter above, and a jellyfin debug log that's from the same time interval as the packet capture.

Firewall misconfiguration is the thing I'd bet my money on atm if I had to. If you hadn't allowed 1900 through, or allowed 1900/tcp because of a brain fart (happens to the best of us), well, then the `ssdp:discover` requests would never reach the server, while alive messages coming from the server or responses to the server's own `ssdp:discover` requests obviously wouldn't be subject to firewall rules, since they would be outgoing.

**Comment by philS1** [comment]
I filtered with the filter suggested by @disgustipated see my attached zip file.
[jelly2.zip](https://github.com/user-attachments/files/17531729/jelly2.zip)

Here you can see thet port section of my docker-compose
`    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional`

However I thought as long as  network_mode: "host" is configured, those port mappings wouldn't be applied.
In iptables I see nothing suspicious.

**Comment by philS1** [comment]
OK it's working now. Thank you all for your great support.
You won't believe what the problem was.
I always did the restarts from the jellyfin web ui. After restarting the docker container it's working.

**Comment by szotsaki** [comment]
I tried the new version, but it didn't work for me, unfortunately. Here are the [start-up logs](https://paste.opensuse.org/pastes/569452343056).

Error message:

```
[INF] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Registering publisher for "urn:schemas-upnp-org:device:MediaServer:1" on "127.0.0.1" with uri "http://127.0.0.1:8096/dlna/8900d942-6e02-479f-aa36-5699a18a865c/description.xml"
[DBG] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: "Device Added MediaServer - 8900d942-6e02-479f-aa36-5699a18a865c - http://127.0.0.1:8096/dlna/8900d942-6e02-479f-aa36-5699a18a865c/description.xml"
[ERR] [1] Jellyfin.Plugin.Dlna.Main.DlnaHost: Error registering endpoint
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at System.UriBuilder..ctor(String uri)
   at Jellyfin.Plugin.Dlna.Main.DlnaHost.RegisterServerEndpoints()
   at Jellyfin.Plugin.Dlna.Main.DlnaHost.StartDevicePublisher(DlnaPluginConfiguration options)
```

Network.xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<NetworkConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <BaseUrl />
  <EnableHttps>false</EnableHttps>
  <RequireHttps>false</RequireHttps>
  <InternalHttpPort>8096</InternalHttpPort>
  <InternalHttpsPort>8920</InternalHttpsPort>
  <PublicHttpPort>8096</PublicHttpPort>
  <PublicHttpsPort>8920</PublicHttpsPort>
  <AutoDiscovery>true</AutoDiscovery>
  <EnableUPnP>false</EnableUPnP>
  <EnableIPv4>true</EnableIPv4>
  <EnableIPv6>true</EnableIPv6>
  <EnableRemoteAccess>true</EnableRemoteAccess>
  <LocalNetworkSubnets>
    <string>192.168.1.0/24</string>
  </LocalNetworkSubnets>
  <LocalNetworkAddresses>
    <string>192.168.1.110</string>
  </LocalNetworkAddresses>
  <KnownProxies />
  <IgnoreVirtualInterfaces>true</IgnoreVirtualInterfaces>
  <VirtualInterfaceNames>
    <string>veth</string>
  </VirtualInterfaceNames>
  <EnablePublishedServerUriByRequest>false</EnablePublishedServerUriByRequest>
  <PublishedServerUriBySubnet>
    <string>http://192.168.1.110:8096</string>
  </PublishedServerUriBySubnet>
  <RemoteIPFilter />
  <IsRemoteIPFilterBlacklist>false</IsRemoteIPFilterBlacklist>
</NetworkConfiguration>
```
