### ISSUE TITLE
Incorrect DLNA server IP for container use

### ISSUE THREAD

**Issue by raxbg** [jellyfin/jellyfin-plugin-dlna#69]
It seems like it is hardcoded that the DLNA server listens on `239.255.255.250`. When running inside a docker container whose network mode is NOT `host` this becomes an issue. Is it possible to add support for overriding this via ENV variable?

I am running multiple containers with DLNA functionality on the same host, so I have a proxy on the host which duplicates anything received on port 1900 to all containers that have DLNA servers. However Jellyfin doesn't appear to play ball probably due to the hardcoded IP.

**Comment by cvium** [comment]
That is the SSDP multicast address. We don't support non-host networks.

**Comment by raxbg** [comment]
Fair, but in an age where containerized applications are gaining popularity I feel like supporting non-host networks should be considered at least :man_shrugging:

**Comment by cvium** [comment]
DLNA and SSDP are messy protocols where every client and server violates the spec in one way or another. I am not opposed to having the support if it is easy and stable, but it's not something we have any plans on doing ourselves
