### ISSUE TITLE
Increase IP TTL from 1 to 2

### ISSUE THREAD

**Issue by Haennetz** [jellyfin/jellyfin-plugin-dlna#73]
Hey at the moment the DLNA packages on port 1900 (SDDP) have a TTL of 1.
If you want to us the DLNA server in a multi VLAN environment the packages got dropped because after hitting the first routing instance the TTL will be decreased by 1 which results in a TTL of 0 and the package get dropped.

It would also be possible to make the TTL configurable.
Thanks a lot for the effort.

**Comment by Nullcaller** [comment]
DLNA is kind of notorious for TTL values being low. IMO the best option is to use firewall(s) to change TTL value on DLNA packets. You can do it on routers in the prerouting chain, or probably on DLNA server hosts in the postrouting chain. Personally, I just have firewall rules set up across my entire home network that increment the TTL of any UDP packet passing through any router with a destination port of 1900, up by 7. This way, I don't ever have to worry about DLNA TTL. I also have similar rules for IGMP (identified by protocol field) and mDNS (identified by proto=UDP and port=5353).

**Comment by disgustipated** [comment]
It looks like the ttl used should be 4, are you seeing a 1 in a wireshark trace?

**Comment by Nullcaller** [comment]
I re-reviewed my packet captures I made for #81, and it appears that `ssdp:alive` and `ssdp:discover` messages do indeed have a TTL value of 1. Despite the TTL value clearly being set to 4 in the plugin source code...

Fun.

**Comment by Nullcaller** [comment]
I'm gonna try and change the default TTL, see if that helps at all, and report back.

**Comment by Nullcaller** [comment]
I set `SsdpDefaultMulticastTimeToLive` to 16 in `SsdpConstants`, this doesn't appear to do anything, TTL still at 1.

**Comment by Nullcaller** [comment]
Seems like TTL is getting reset somewhere. I added

```
socket.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.MulticastTimeToLive, _MulticastTtl);
```

before 

```
await socket.SendToAsync(messageData, destination, cancellationToken).ConfigureAwait(false);
```

in `SendFromSocket` in `SsdpCommunicationsServer`, and it figured itself out. TTL is 4 on outgoing SSDP packets.

**Comment by Nullcaller** [comment]
Yeah, no. There are 'listen sockets' (`_MulticastListenSockets`) which are created in `CreateUdpMulticastSocket`, and there are 'send sockets' (`_sendSockets`) which are created in `CreateSsdpUdpSocket`. TTL is set for listen sockets, but not for send sockets, and thus defaults to 1.
