### ISSUE TITLE
Support for commedia (Meta Quest 2/3)

### ISSUE THREAD

**Issue by philS1** [jellyfin/jellyfin-plugin-dlna#87]
Hi,

there is a new meta video player available supporting DLNA.
I can browse the jellyfin folder structure but each folder no media is found.
I made a wireshark dump, maybe it's just a little issue with the media type description in the xml files?
[commedia.zip](https://github.com/user-attachments/files/17534047/commedia.zip)

192.168.178.99 is the quest3,
192.168.178.79 is the server.

**Comment by Nullcaller** [comment]
I think your filter is too restrictive, your packet capture doesn't include any POST requests Commedia makes to actually browse the directory structure, and the responses of the Jellyfin DLNA plugin. I made my own packet capture (I'm running a modified version of the plugin that works with Bigscreen, see #83), and everything seems in order, despite Commedia not displaying any files. DIDL looks like this:

```
<DIDL-Lite
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/"
	xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"
	xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/">
	<item restricted="1" id="69e37c5cf4b43bd45ee10bba0f9b4ef1" parentID="movies_f137a2dd21bbc1b99aa5c0f6bf02a805">
		<dc:title>...</dc:title>
		<upnp:class>object.item.videoItem.movie</upnp:class>
		<dc:date>...</dc:date>
		<upnp:genre>...</upnp:genre>
		...
		<upnp:genre>...</upnp:genre>
		<dc:description>...</dc:description>
		<res duration="..." size="..." nrAudioChannels="6" resolution="1920x800" sampleFrequency="48000" bitrate="11686573" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_PN=MATROSKA;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=21D00000000000000000000000000000">http://10.x.x.x:8096/dlna/videos/69e37c5c-f4b4-3bd4-5ee1-0bba0f9b4ef1/stream.mkv?DeviceProfileId=b5c0e68848ce4d1daf5ae300e79f0c59&amp;amp;DeviceId=test&amp;amp;MediaSourceId=69e37c5cf4b43bd45ee10bba0f9b4ef1&amp;amp;Static=true&amp;amp;VideoCodec=h264&amp;amp;AudioCodec=dts&amp;amp;AudioStreamIndex=2&amp;amp;Tag=620f0c4402bcb8eccfce469ace159db5&amp;amp;dlnaheaders=true</res>
		<upnp:albumArtURI dlna:profileID="JPEG_SM">http://10.x.x.x:8096/Items/69e37c5cf4b43bd45ee10bba0f9b4ef1/Images/Primary/0/5e89cb9a19147434d5a2c1363a2c2fd0/jpg/480/480/0/0</upnp:albumArtURI>
		<upnp:icon>http://10.x.x.x:8096/Items/69e37c5cf4b43bd45ee10bba0f9b4ef1/Images/Primary/0/5e89cb9a19147434d5a2c1363a2c2fd0/jpg/48/48/0/0</upnp:icon>
	</item>
	...
</DIDL-Lite>
```

The SOAP envelope XML also looks fine. Numbers returned, total matches — everything's in order. So yeah, seems like Commedia can't properly interpret DIDL.

**Comment by Nullcaller** [comment]
Plex works. So here's Plex's DIDL:

```
<DIDL-Lite
	xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"
	xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/">
	<item id="e11d78f1f4e6990730a5" parentID="62502ddbf968b05101ba" restricted="1">
		<dc:title>...</dc:title>
		<dc:creator>...</dc:creator>
		<dc:date>...</dc:date>
		<upnp:actor>...</upnp:actor>
		...
		<upnp:actor>...</upnp:actor>
		<upnp:genre>...</upnp:genre>
		...
		<upnp:genre>...</upnp:genre>
		<upnp:albumArtURI dlna:profileID="JPEG_MED">http://10.x.x.x:32469/proxy/887130febfc7a0080504/albumart.jpg</upnp:albumArtURI>
		<dc:description>...</dc:description>
		<upnp:longDescription>...</upnp:longDescription>
		<upnp:icon>http://10.x.x.x:32469/proxy/96df16683b10be94a604/icon.jpg</upnp:icon>
		<res duration="..." size="..." resolution="1920x800" bitrate="1268375" nrAudioChannels="6" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01500000000000000000000000000000">http://10.x.x.x:32469/object/e11d78f1f4e6990730a5/file.mkv</res>
		<upnp:class>object.item.videoItem.movie</upnp:class>
	</item>
	...
</DIDL-Lite>
```

**Comment by Nullcaller** [comment]
Also, this is the DIDL that the DLNA plugin returns for 'Movies' folder (which obviously gets interpreted correctly):
```

<DIDL-Lite
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/"
	xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/"
	xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/">
	<container restricted="1" searchable="1" childCount="0" id="continuewatching_f137a2dd21bbc1b99aa5c0f6bf02a805" parentID="f137a2dd21bbc1b99aa5c0f6bf02a805">
		<dc:title>Continue Watching</dc:title>
		<upnp:class>object.container.storageFolder</upnp:class>
		<upnp:albumArtURI dlna:profileID="JPEG_SM">http://10.x.x.x:8096/Items/f137a2dd21bbc1b99aa5c0f6bf02a805/Images/Primary/0/b2995131b6bf13230bbf921076010cae/jpg/480/480/0/0</upnp:albumArtURI>
		<upnp:icon>http://10.x.x.x:8096/Items/f137a2dd21bbc1b99aa5c0f6bf02a805/Images/Primary/0/b2995131b6bf13230bbf921076010cae/jpg/48/48/0/0</upnp:icon>
		<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_LRG;DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=00D00000000000000000000000000000" resolution="960x540">http://10.x.x.x:8096/Items/f137a2dd21bbc1b99aa5c0f6bf02a805/Images/Primary/0/b2995131b6bf13230bbf921076010cae/jpg/4096/4096/0/0</res>
		...
		<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_OP=00;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=00D00000000000000000000000000000" resolution="160x90">http://10.x.x.x:8096/Items/f137a2dd21bbc1b99aa5c0f6bf02a805/Images/Primary/0/b2995131b6bf13230bbf921076010cae/jpg/160/160/0/0</res>
	</container>
	...
</DIDL-Lite>
```

**Comment by Nullcaller** [comment]
Is it possible that Commedia just doesn't like `&amp;`s in the URI?

**Comment by philS1** [comment]
I'm already using your modified version that works with Bigscreen.
I removed the filter from the original pcap and I don't see any HTTP Post commands, there's only get and 200 OK messages.

So if there's no &amp; supported it should be fixed on the commedia app and not on the dlna plugin right?
How can we contact commedia devs?

**Comment by Nullcaller** [comment]
Well, post commands should be there, otherwise you wouldn't be able to see any folders at all. Maybe Commedia caches directory structure?

As for `&amp;`s, currently, this is only a guess. Give me a bit of time, I'll make the plugin send links without ampersands and see if that makes Commedia at least list the contents.

**Comment by Nullcaller** [comment]
Yup. Tested it. This thing doesn't like ampersands.

**Comment by Nullcaller** [comment]
Btw, if you're using my version, 4.0.0.0 with bigscreen compat can be found [on GitHub actions of my fork](https://github.com/Nullcaller/jellyfin-plugin-dlna/actions/runs/11544370672) or as a zip file: [build-artifact.zip](https://github.com/user-attachments/files/17535652/build-artifact.zip).

**Comment by Nullcaller** [comment]
You should probably report the bug to Commedia [here](https://docs.commedia.app/support). It should be fairly easy for them to fix.

**Comment by Nullcaller** [comment]
I reported the bug in Commedia's Discord server, and linked this issue.

**Comment by commedia-player** [comment]
Hey @philS1 @Nullcaller, 

thanks for reporting, fix is up on new Beta. 
Issue: https://github.com/commedia-player/Commedia/issues/1

Please let us know if it works, thanks!

Commedia

**Comment by Nullcaller** [comment]
@commedia-player, thank you so much, it works! This is awesome!

**Comment by crobibero** [comment]
Closing as fixed upstream
