### ISSUE TITLE
Can not install 4 or 5 on 10.9.11 FreeBSD manually

### ISSUE THREAD

**Issue by make-nz** [jellyfin/jellyfin-plugin-dlna#99]
Can not install 4 or 5 on 10.9.11 FreeBSD manually. Rebooting detects the plugin, bur has no config/settings an no avaiable devices in the cast to menu.
(Last working version is dlna_3.0.0.0)

![Image](https://github.com/user-attachments/assets/83d7884e-e3ec-481f-b9a6-a6ab9e4e32e5)

![Image](https://github.com/user-attachments/assets/f0e891e3-6ea5-4bc5-a619-655b5c8c9c8b)

![Image](https://github.com/user-attachments/assets/63aee68f-dd10-4347-a3fe-a23135166560)

**Comment by thornbill** [comment]
Versions 4 and newer require server version 10.10.
